### PR TITLE
255 graph tweaks

### LINKED ISSUE #255: [Bug]: graph issues
## Description

image

- central alignment doesn't account for labels
- labels overflowing at around 1400 px
- title should be `firs neue` font
- missing vertical / x markers where data points at edge don't land on  a whole unit
- color collision between blues and reds which are hard to tell apart 

## Steps to reproduce
1. What you did first
1. What you did next

## Platform (if relevant)
What device and browser were you using?

### PR DESCRIPTION
**Pull request by aaaaargZombies**
Fixes #255

## Description

- calculate size of longest y axis label and add padding to container, this pushes everything in the right direction but as it uses `ch` units which are based off the base font size it will only fall into perfect alignment at a sweetspot as the SVG text grows and shrinks with the screen size.
- legend now limited to 90% of the svg width and wraps on to a new line when it needs to, conveniently you can pass arbitrary html attributes to this so could just add a class and use normal CSS
- I've switched all the fonts to `TT firs neue`, unfortunately I wasn't able to target just the title. You can't pass in a class and for some reason `first-child` didn't seem to effect it. Hopefully this is an improvement
- A buffer of time is applied to the X axis
- Section 2 and 5 get the chosen colors, the telegram graph reverts to defaults which I think just evenly spaces the color spectrum to get better separation.
- I reduced the number of generated X axis label points because when I added in the time buffer the graph that spanned more years started to have overlapping labels
- I looked into forcing a vertical line on the right hand side, it wasn't possible in the chart library. It was possible to add a single border with CSS but it looked worse than leaving it out.

I think that covers all the issues with a couple of compromises!

image

### CODE REVIEW

File: src/elm/View/Graph.elm [hunk 1]
```diff
@@ -20,169 +21,205 @@ view model sectionId =
         graph =
             List.head (Data.filterBySection sectionId model.content.graphs)
                 |> Maybe.withDefault Data.lineChartData
+
+        yAxisLabelPadding =
```
Comment (katjam) [inline src/elm/View/Graph.elm:25]: Neat!

File: src/elm/View/Graph.elm [hunk 2]
```diff
@@ -208,17 +245,65 @@ allDates dataPoints =
...
-dateRangeEnd dataPoints =
+dateRangeEnd : Data.SectionId -> List Data.LineChartDatum -> Float
+dateRangeEnd id dataPoints =
     List.reverse (allDates dataPoints)
         |> List.head
         |> Maybe.withDefault (toFloat 1672531200000)
+        |> ceilingDate id
+
+
+oneYearInMiliseconds : Int
```
Comment (katjam) [inline src/elm/View/Graph.elm:263]: I think milis needs to be millis everywhere. 2 l's but otherwise this looks great.
